package com.kz.valocheck.repo

import com.kz.valocheck.R
import com.kz.valocheck.domain.*
import javax.inject.Inject

class WeaponsRepo @Inject constructor() {

    private val mockWeaponList = listOf(
        WeaponsDomain(
            "1",
            "Classic",
            "Sidearm",
            R.drawable.weapon_classic_display_icon,
                WeaponStatsDomain(
                    "6.75",
                    "12",
                    "0.85",
                    "0.75",
                    "1.75",
                    "Low",
                    "SemiAutomatic"
            ),
                ShopDataDomain(
                    "0",
                    "Pistols",
                    "Sidearms"
            ),
                DamageRangeDomain(
                        Range0To30Domain(
                            "78",
                            "26",
                            "22.1",
                    ),
                        Range30To50Domain(
                            "66",
                            "22",
                            "18.7"
                    )
                )
            ),
        WeaponsDomain(
            "2",
            "Classic2",
            "Sidearm",
            R.drawable.weapon_classic_display_icon,
            WeaponStatsDomain(
                "6.75",
                "12",
                "0.85",
                "0.75",
                "1.75",
                "Low",
                "SemiAutomatic"
            ),
            ShopDataDomain(
                "0",
                "Pistols",
                "Sidearms"
            ),
            DamageRangeDomain(
                Range0To30Domain(
                    "78",
                    "26",
                    "22.1",
                ),
                Range30To50Domain(
                    "66",
                    "22",
                    "18.7"
                )
            )
        ),
        WeaponsDomain(
            "3",
            "Classic3",
            "Sidearm",
            R.drawable.weapon_classic_display_icon,
            WeaponStatsDomain(
                "6.75",
                "12",
                "0.85",
                "0.75",
                "1.75",
                "Low",
                "SemiAutomatic"
            ),
            ShopDataDomain(
                "0",
                "Pistols",
                "Sidearms"
            ),
            DamageRangeDomain(
                Range0To30Domain(
                    "78",
                    "26",
                    "22.1",
                ),
                Range30To50Domain(
                    "66",
                    "22",
                    "18.7"
                )
            )
        ),
        WeaponsDomain(
            "4",
            "Classic4",
            "Sidearm",
            R.drawable.weapon_classic_display_icon,
            WeaponStatsDomain(
                "6.75",
                "12",
                "0.85",
                "0.75",
                "1.75",
                "Low",
                "SemiAutomatic"
            ),
            ShopDataDomain(
                "0",
                "Pistols",
                "Sidearms"
            ),
            DamageRangeDomain(
                Range0To30Domain(
                    "78",
                    "26",
                    "22.1",
                ),
                Range30To50Domain(
                    "66",
                    "22",
                    "18.7"
                )
            )
        ),
        WeaponsDomain(
            "5",
            "Classic5",
            "Sidearm",
            R.drawable.weapon_classic_display_icon,
            WeaponStatsDomain(
                "6.75",
                "12",
                "0.85",
                "0.75",
                "1.75",
                "Low",
                "SemiAutomatic"
            ),
            ShopDataDomain(
                "0",
                "Pistols",
                "Sidearms"
            ),
            DamageRangeDomain(
                Range0To30Domain(
                    "78",
                    "26",
                    "22.1",
                ),
                Range30To50Domain(
                    "66",
                    "22",
                    "18.7"
                )
            )
        ),
        WeaponsDomain(
            "6",
            "Classic6",
            "Sidearm",
            R.drawable.weapon_classic_display_icon,
            WeaponStatsDomain(
                "6.75",
                "12",
                "0.85",
                "0.75",
                "1.75",
                "Low",
                "SemiAutomatic"
            ),
            ShopDataDomain(
                "0",
                "Pistols",
                "Sidearms"
            ),
            DamageRangeDomain(
                Range0To30Domain(
                    "78",
                    "26",
                    "22.1",
                ),
                Range30To50Domain(
                    "66",
                    "22",
                    "18.7"
                )
            )
        ),
        WeaponsDomain(
            "7",
            "Classic7",
            "Sidearm",
            R.drawable.weapon_classic_display_icon,
            WeaponStatsDomain(
                "6.75",
                "12",
                "0.85",
                "0.75",
                "1.75",
                "Low",
                "SemiAutomatic"
            ),
            ShopDataDomain(
                "0",
                "Pistols",
                "Sidearms"
            ),
            DamageRangeDomain(
                Range0To30Domain(
                    "78",
                    "26",
                    "22.1",
                ),
                Range30To50Domain(
                    "66",
                    "22",
                    "18.7"
                )
            )
        )
    )

    fun getWeaponsList(): List<WeaponsDomain> {
        return mockWeaponList
    }

    fun getWeaponsDetail(id: String) : WeaponsDomain {
        return mockWeaponList.find { it.id == id }!!
    }

}